dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"

install: 
   - pip3 install --upgrade pip 
   - pip install coveralls
   - npm install lcov-parse

script: 
 python -c "1"

after_success:
 - coveralls
notifications:
  webhooks:
    - http://178.141.188.97:8000/api/v1/challenge/check_builds/
